# Generated by Django 2.1 on 2019-08-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('editors_choice', models.CharField(max_length=20)),
            ],
        ),
    ]
